version: '3'

services:
  dbos:
    image : mysql:5.7
    volumes: 
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_USER: sathvika
       MYSQL_PASSWORD: redhat
       MYSQL_DATABASE: mydb


  ghostos:
    image: ghost:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 8082:2368
    environment:
      database__connection__host: dbos
      database__connection__user: sathvika
      database__connection__password: redhat
      database__connection__database: mydb
    volumes:
      - gh_storage:/contest/adapter/storage

volumes:
    gh_storage:
    mysql_storage:
